FROM golang:1.25 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o portal-service ./cmd/portal

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /app/portal-service /app/portal-service
COPY --from=builder /app/portal /app/portal

EXPOSE 5000

CMD ["/app/portal-service"]