FROM golang:1.25 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o grades-service ./cmd/gradingservice

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /app/grades-service /app/grades-service
COPY --from=builder /app/docs /app/docs

EXPOSE 6000

CMD ["/app/grades-service"]